---
- name: Server Hardening
  hosts: vault_pi
  become: yes

  vars_files:
    - config.yml
    - vars/log2ram.yml

  pre_tasks:
    - name: pre tasks
      import_tasks: tasks/pre.yml

  handlers:
    - name: handlers for log2ram
      import_tasks: handlers/log2ram_restart.yml

  tasks:
    - name: Setup log2ram
      import_tasks: tasks/security/log2ram.yml

    - name: Setup User Security
      import_tasks: tasks/security/users.yml

    - name: Setup SSH Security
      import_tasks: tasks/security/ssh.yml

    - name: Setup Firewall
      import_tasks: tasks/security/firewall.yml

    - name: Setup Auto-Updates
      import_tasks: tasks/security/autoupdate.yml
      when: ensure_autoupdate

- name: Backup Management
  hosts: vault_pi
  become: yes

  vars_files:
    - config.yml
    - vars/backups.yml

  handlers:
    - name: Include Sync-Restore Handlers
      import_tasks: handlers/sync_restore.yml

    - name: Include Backup-Restore Handlers
      import_tasks: handlers/backup_restore.yml

    - name: Include Scheduling Handlers
      import_tasks: handlers/schedule_backups.yml

  tasks:
    - name: Setup Rclone
      import_tasks: tasks/backups/rclone.yml
      when: ensure_backup

    - name: Setup BorgBackup
      import_tasks: tasks/backups/borg.yml
      when: ensure_backup

    - name: Setup Backups and Sync Scripts
      import_tasks: tasks/backups/scheduling.yml
      when: ensure_backup

- name: E-Ink Display Management
  hosts: vault_pi
  become: yes

  vars_files:
    - config.yml
    - vars/display.yml

  handlers:
    - name: Include Waveshare Driver Handlers
      import_tasks: handlers/waveshare_driver.yml

  tasks:
    - name: Setup SPI
      import_tasks: tasks/display/spi.yml
      when: ensure_display

    - name: Setup Display Refresh Scripts
      import_tasks: tasks/display/display.yml
      when: ensure_display

- name: Container Setup
  hosts: vault_pi
  become: yes

  vars_files:
    - config.yml

  post_tasks:
    - name: Filesystem Cleanup
      import_tasks: tasks/post.yml

  handlers:
    - name: Include Docker Handlers
      import_tasks: handlers/docker_restart.yml

  tasks:
    - name: Setup Docker
      import_tasks: tasks/containers/docker.yml

    - name: Setup Containers
      import_tasks: tasks/containers/containers.yml
