---
- name: Remove temporary openssl configs
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/openssl.cnf
    - /tmp/openssl.conf

- name: Remove ansible tmp dir for user
  file:
    path: "/home/{{ ansible_user }}/.ansible/tmp"
    state: absent

- name: Reboot system
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

- name: Wait for reboot to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 15
    timeout: 600
