---
- name: Ensure dependencies for waveshare module are installed
  ansible.builtin.apt:
    name: 
      - git
      - python3-pip
      - python3-numpy
    state: present
  listen: "waveshare init"

- name: Check if waveshare module repository exists
  stat:
    path: "{{ base_path }}/{{ display.scripts_path }}/{{ display.driver.local_path }}"
  register: waveshare_repo
  listen: "waveshare init"

- name: Ensure waveshare module is cloned
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: "{{ display.driver.git_repo }}"
    dest: "{{ base_path }}/{{ display.scripts_path }}/{{ display.driver.local_path }}"
  when: waveshare_repo.stat.exists == False
  listen: "waveshare init"

- name: Ensure waveshare module is installed
  pip:
    name: file://{{ base_path }}/{{ display.scripts_path }}/{{ display.driver.pip_module }}
  when: waveshare_repo.stat.exists == False
  listen: "waveshare init"
